version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: actix
    versions:
    - 0.11.0
    - 0.11.1
  - dependency-name: docopt
    versions:
    - 1.1.1
  - dependency-name: actix-rt
    versions:
    - 2.0.0
    - 2.0.2
    - 2.1.0
    - 2.2.0
  - dependency-name: postgres
    versions:
    - 0.19.1
  - dependency-name: serde
    versions:
    - 1.0.124
    - 1.0.125
  - dependency-name: env_logger
    versions:
    - 0.8.3
  - dependency-name: criterion
    versions:
    - 0.3.4
