# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# exclusions should be separated with a pipe (|) character and a newline
exclude: |
  (?x)^(
      tests/expected/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust Format
        description: "Automatically format Rust code with cargo fmt"
        entry: sh -c "cargo fmt --all"
        language: rust
        pass_filenames: false

# TODO: Add SQL hooks for formatting and linting
# TODO: Add NPM hooks for formatting and linting
