[workspace]
default-members = ["martin-tile-utils", "."]
members = ["martin-tile-utils"]

[package]
name = "martin"
version = "0.7.0-alpha"
edition = "2021"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>", "Yuri Astrakhan <YuriAstrakhan@gmail.com>", "MapLibre contributors"]
description = "Blazing fast and lightweight PostGIS vector tile server"
repository = "https://github.com/maplibre/martin"
license = "MIT OR Apache-2.0"

[lib]
name = "martin"
path = "src/lib.rs"

[[bin]]
name = "martin"
path = "src/bin/main.rs"

[features]
default = []
ssl = ["openssl", "postgres-openssl"]
vendored-openssl = ["ssl", "openssl/vendored"]

[dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-http = "3"
actix-rt = "2"
actix-web = "4"
async-trait = "0.1"
bb8 = "0.8"
bb8-postgres = "0.8"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
futures = "0.3"
itertools = "0.10"
log = "0.4"
martin-tile-utils = { path = "martin-tile-utils" }
num_cpus = "1"
openssl = { version = "0.10", optional = true }
postgis = "0.9"
postgres = { version = "0.19", features = ["with-time-0_3", "with-uuid-1", "with-serde_json-1"] }
postgres-openssl = { version = "0.5", optional = true }
postgres-protocol = "0.6"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
subst = { version = "0.2", features = ["yaml"] }
thiserror = "1"
tilejson = "0.3"

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }
criterion = { version = "0.4", features = ["async_futures", "async_tokio", "html_reports"] }
ctor = "0.1"
indoc = "1"
#test-log = "0.2"

[[bench]]
name = "sources"
harness = false
