[package]
name = "martin"
version = "1.0.0-alpha.0"
edition = "2021"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>", "MapLibre contributors"]
description = "Blazing fast and lightweight PostGIS vector tiles server"
repository = "https://github.com/maplibre/martin/"
license = "MIT OR Apache-2.0"

[lib]
name = "martin"
path = "src/lib.rs"

[[bin]]
name = "martin"
path = "src/bin/main.rs"

[dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-http = "3"
actix-rt = "2"
actix-web = "4"
async-trait = "0.1"
bb8 = "0.8"
bb8-postgres = "0.8"
docopt = "1"
env_logger = "0.9"
itertools = "0.10"
log = "0.4"
num_cpus = "1"
openssl = "0.10"
postgis = "0.9"
postgres = { version = "0.19", features = ["with-time-0_2", "with-uuid-0_8", "with-serde_json-1"] }
postgres-openssl = "0.5"
postgres-protocol = "0.6"
semver = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.9"
tilejson = "0.3"

[dev-dependencies.criterion]
version = "0.3.4"
features = ["async_futures", "async_tokio", "html_reports"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "prepush-hook", "run-cargo-fmt", "run-cargo-clippy", "run-cargo-test"]

[[bench]]
name = "sources"
harness = false
