[build]
pre-build = [
    # install nodejs and npm to compile static web resources
    # note that architecture could be the same as the container, not $CROSS_DEB_ARCH
    "curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh",
    "bash nodesource_setup.sh",
    "apt-get install -y nodejs",
    "node -v",
]
