[build]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_17.x -o nodesource_setup.sh",
    "bash nodesource_setup.sh",
    "apt-get install -y nodejs",
    "node -v",
    # Using old NPM, so must ensure correct access
    "mkdir -p /.npm",
    "chown -R 1001:127 /.npm",
]
