version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["npm", "run", "preview"]
    depends_on:
      - tiles
    ports:
      - "80:8080"

  tiles:
    image: arm64martinimage
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres@db/db
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/db:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
