[package]
name = "martin-mbtiles"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
log = "0.4"
martin-tile-utils = { path = "../martin-tile-utils" }
serde_json = "1"
sqlx = { version = "0.6", features = ["offline", "sqlite", "runtime-actix-native-tls"] }
thiserror = "1"
tilejson = "0.3"

[dev-dependencies]
# For testing, might as well use the same async framework as the Martin itself
actix-rt = "2"
