name: CI Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on non-container PostGIS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md

      - name: Start postgres
        uses: nyurik/action-setup-postgis@main
        id: pg
        with:
          username: test
          password: test
          database: test
          rights: --superuser

      - name: Init DB
        run: tests/fixtures/initdb.sh
        shell: bash

      - name: Cargo tests
        run: cargo test --all
        shell: bash
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}

      - name: Integration tests
        run: tests/test.sh
        shell: bash
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}
