name: CI MacOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - name: Install postgis
        run: brew install postgis

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Start postgres
        uses: nyurik/action-setup-postgres@master
        id: pg
        with:
          username: test
          password: test
          database: test
          rights: --superuser

      - name: Init DB
        run: tests/fixtures/initdb.sh
        shell: bash

      - name: Cargo tests
        run: cargo test --all
        shell: bash
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}

      - name: Integration tests
        run: tests/test.sh
        shell: bash
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}
