name: MacOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    branches: [main]

jobs:
  test:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - name: Install postgis
        run: brew install postgis

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Start postgres
        uses: ikalnytskyi/action-setup-postgres@v3
        id: pg

      - name: Run tests
        run: |
          echo "Recreating postgres user as a superuser"
          dropuser postgres
          createuser -s postgres
          echo "**************************** Init database"
          tests/fixtures/initdb.sh
          echo "**************************** Cargo tests"
          cargo test --all
          echo "**************************** Integration tests"
          tests/test.sh
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}
