name: MacOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - name: Install postgis
        run: brew install postgis

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Start postgres
        uses: nyurik/action-setup-postgres@master
        id: pg
        with:
          username: test
          password: test
          database: test
          rights: --superuser

      - name: Init DB
        run: |
          tests/fixtures/initdb.sh
#        env:
#          PGDATABASE: ${{ steps.pg.outputs.connection-uri }}
        shell: bash

      - name: Cargo tests
        run: |
          cargo test --all
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}
        shell: bash

      - name: Integration tests
        run: |
          tests/test.sh
        env:
          DATABASE_URL: ${{ steps.pg.outputs.connection-uri }}
        shell: bash
